apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - ../../base

# Use local-path storage class
patches:
  - target:
      kind: PersistentVolumeClaim
      name: jenkins-home-pvc
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: local-path
