apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jenkins

resources:
  - namespace.yaml
  - service-accounts.yaml
  - pvcs.yaml
  - deployment.yaml
  - httproute.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: jenkins
    includeSelectors: false

images:
  - name: jenkins/jenkins
    newTag: lts
  - name: docker
    newTag: dind
